version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.1
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: cd backend-go && GO111MODULE=on go get -v -t -d ./...
      - run: cd godog && GO111MODULE=on go get -v -t -d ./...
  test:
    docker:
      - image: circleci/golang:1.15.1
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: cd backend-go && go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test